// Generated by CoffeeScript 1.8.0
module.exports = {
  DiffPool: require('./src/diff-pool'),
  Watch: require('./src/watch'),
  Service: require('./src/service'),
  AllServices: require('./src/allservices'),
  AgentServices: require('./src/agentservices'),
  KV: require('./src/kv'),
  FindReplace: require('./src/find-replace')
};
