// Generated by CoffeeScript 1.9.2
module.exports = {
  DiffPool: require('./src/diff-pool'),
  Watch: require('./src/watch'),
  Service: require('./src/service'),
  AllServices: require('./src/allservices'),
  AgentServices: require('./src/agentservices'),
  KV: require('./src/kv'),
  GetKV: require('./src/getkv'),
  SetKV: require('./src/setkv'),
  FindReplace: require('./src/find-replace'),
  Session: require('./src/session'),
  TTLSession: require('./src/ttlsession'),
  WatchSession: require('./src/watchsession'),
  Lock: require('./src/lock')
};
