// Generated by CoffeeScript 1.8.0
module.exports = {
  ConsulWatch: require('./src/consul-watch'),
  DiffPool: require('./src/diff-pool'),
  RedWireConsulService: require('./src/redwire-consul-service')
};
