// Generated by CoffeeScript 1.9.2
var consul, hub, worker;

consul = require('./');

hub = require('odo-hub');

hub = hub.create();

worker = function(httpAddr, prefix) {
  var session, watch;
  session = consul.TTLSession(httpAddr);
  watch = new consul.KV(httpAddr, prefix, {
    recurse: true
  }, function(keys) {
    keys = keys.filter(function(k) {
      return k.Key !== prefix;
    });
    return console.log(keys);
  });
  session.run({
    onup: function() {
      return console.log('onup');
    },
    ondown: function() {
      return console.log('ondown');
    }
  });
  return {
    destroy: function() {
      session.destroy();
      return watch.end();
    }
  };
};

worker = worker('docker:8500', 'sagas/');

process.on('SIGINT', function() {
  return worker.destroy();
});
