// Generated by CoffeeScript 1.9.2
var http;

http = require('http');

module.exports = function(params, content, cb) {
  var req;
  req = http.request(params, function(res) {
    var body, error;
    res.setEncoding('utf8');
    if (res.statusCode !== 200) {
      error = '';
      res.on('data', function(data) {
        return error += data;
      });
      return res.on('end', function() {
        return cb(error);
      });
    }
    body = '';
    res.on('data', function(data) {
      return body += data;
    });
    return res.on('end', function() {
      return cb(null, JSON.parse(body));
    });
  }).on('error', cb);
  if (content != null) {
    req.setHeader('Content-Type', 'application/json');
    req.setHeader('Content-Length', Buffer.byteLength(content));
    req.write(content);
  }
  return req.end();
};
