// Generated by CoffeeScript 1.9.2
var DiffPool, Service, Watch,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Watch = require('./watch');

DiffPool = require('./diff-pool');

module.exports = Service = (function() {
  function Service(httpAddr, serviceId, callback) {
    this.distributeTls = bind(this.distributeTls, this);
    this.distributeTcp = bind(this.distributeTcp, this);
    this.distributeWs = bind(this.distributeWs, this);
    this.distributeHttps = bind(this.distributeHttps, this);
    this.distributeHttp = bind(this.distributeHttp, this);
    this.distribute = bind(this.distribute, this);
    this.next = bind(this.next, this);
    this.members = bind(this.members, this);
    this.end = bind(this.end, this);
    this._index = 0;
    this._pool = new DiffPool(callback);
    this._watch = new Watch(httpAddr + "/v1/catalog/service/" + serviceId, (function(_this) {
      return function(services) {
        return _this._pool.set(services.map(function(s) {
          return {
            host: s.Node,
            address: s.Address,
            port: s.ServicePort
          };
        }));
      };
    })(this));
  }

  Service.prototype.end = function() {
    return this._watch.end();
  };

  Service.prototype.members = function() {
    return this._pool.members();
  };

  Service.prototype.next = function() {
    var members, result;
    members = this.members();
    if (members.length === 0) {
      return null;
    }
    this._index = this._index % members.length;
    result = members[this._index];
    this._index++;
    return result.address + ":" + result.port;
  };

  Service.prototype.distribute = function() {
    return (function(_this) {
      return function(mount, url, req, res, next) {
        req.target = "http://" + (_this.next());
        return next();
      };
    })(this);
  };

  Service.prototype.distributeHttp = function() {
    return (function(_this) {
      return function(mount, url, req, res, next) {
        req.target = "http://" + (_this.next());
        return next();
      };
    })(this);
  };

  Service.prototype.distributeHttps = function() {
    return (function(_this) {
      return function(mount, url, req, res, next) {
        req.target = "https://" + (_this.next());
        return next();
      };
    })(this);
  };

  Service.prototype.distributeWs = function() {
    return (function(_this) {
      return function(mount, url, req, socket, head, next) {
        req.target = "http://" + (_this.next());
        return next();
      };
    })(this);
  };

  Service.prototype.distributeTcp = function() {
    return (function(_this) {
      return function(req, socket, next) {
        req.target = _this.next();
        return next();
      };
    })(this);
  };

  Service.prototype.distributeTls = function() {
    return (function(_this) {
      return function(req, socket, next) {
        req.target = _this.next();
        return next();
      };
    })(this);
  };

  return Service;

})();
