// Generated by CoffeeScript 1.9.2
var httpput, url_parse;

httpput = require('./httpput');

url_parse = require('url').parse;

module.exports = function(httpAddr, url, contents, cb) {
  var params;
  if (typeof httpAddr === 'string') {
    if (httpAddr.indexOf('http://') !== 0) {
      httpAddr = "http://" + httpAddr;
    }
    httpAddr = url_parse(httpAddr);
  }
  params = {
    hostname: httpAddr.hostname,
    port: httpAddr.port,
    path: "/v1/kv/" + url,
    method: 'PUT'
  };
  return httpput(params, contents, cb);
};
